### ISSUE TITLE
'nimble install nim7z' seems to trim the contents of '/nim7z'

### ISSUE THREAD

**Issue by davidnorthetal** [genotrance/nim7z#1]
Hey,

when installing nim7 via `nimble install nim7z` the 'setup' task steps seem to be executed just fine: 

> $ nimble install nim7z
Downloading https://github.com/genotrance/nim7z using git
Setting up Git repo: https://github.com/kornelski/7z
Pulling repository
Processing nim7z/C/7z.h
  Appending keys for wildcard 7*.h
Processing nim7z/C/7zTypes.h
  Appending keys for wildcard 7*.h
Generating nim7z/svnzTypes.nim
Generating nim7z/svnz.nim
Processing nim7z/C/7zAlloc.h
  Appending keys for wildcard 7*.h
Generating nim7z/svnzAlloc.nim
Processing nim7z/C/7zBuf.h
  Appending keys for wildcard 7*.h
Generating nim7z/svnzBuf.nim
Processing nim7z/C/7zCrc.h
  Appending keys for wildcard 7*.h
Generating nim7z/svnzCrc.nim
Processing nim7z/C/7zFile.h
  Appending keys for wildcard 7*.h
Generating nim7z/svnzFile.nim
Processing nim7z/C/7zVersion.h
  Appending keys for wildcard 7*.h
Generating nim7z/svnzVersion.nim
Processing nim7z/svnz.nim
Processing nim7z/svnzTypes.nim
Processing nim7z/svnzFile.nim
  Verifying dependencies for nim7z@0.1.4
      Info: Dependency on nimgen@>= 0.4.0 already satisfied
  Verifying dependencies for nimgen@0.5.1
      Info: Dependency on c2nim@>= 0.9.14 already satisfied
  Verifying dependencies for c2nim@0.9.14
      Info: Dependency on regex@>= 0.10.0 already satisfied
  Verifying dependencies for regex@0.13.0
      Info: Dependency on unicodedb@>= 0.7.2 already satisfied
  Verifying dependencies for unicodedb@0.7.2
      Info: Dependency on unicodeplus@>= 0.5.0 already satisfied
  Verifying dependencies for unicodeplus@0.5.1
      Info: Dependency on unicodedb@>= 0.7 already satisfied
  Verifying dependencies for unicodedb@0.7.2
 Installing nim7z@0.1.4
   Success: nim7z installed successfully.

but then, the corresponding directory in the `.nimble` misses all those checked-out/converted files in the 'nim7z' dir:

> $HOME/.nimble/pkgs/nim7z-0.1.4
├── nim7z
├── nim7z.nim
├── nim7z.nimble
└── nimblemeta.json
>
> 1 directory, 3 files

but when I clone the repository myself in a fresh directory and do `nimble install` the files are generated fine, hacky temp fix is to copy the `nim7z` directory from there into the `$HOME/.nimble/pkgs/...` directory

Thanks for any reply!

**Comment by genotrance** [comment]
This is because of https://github.com/nim-lang/nimble/issues/549.

Have to clone repo, nimble setup then nimble install to work around.
